import 'package:flutter/material.dart';
import 'package:flutterapp/ezbarterapp/generatedbilingwidget/generated/GeneratedFrame994Widget.dart';
import 'package:flutterapp/ezbarterapp/generatedbilingwidget/generated/GeneratedFrame991Widget.dart';
import 'package:flutterapp/ezbarterapp/generatedbilingwidget/generated/GeneratedComponent7Widget1.dart';

/* Frame Biling
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBilingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 900.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1295.0,
                      height: 900.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 235.0,
                              height: 900.0,
                              child: GeneratedComponent7Widget1(),
                            ),
                            Positioned(
                              left: 242.0,
                              top: 393.0,
                              right: null,
                              bottom: null,
                              width: 751.0,
                              height: 196.0,
                              child: GeneratedFrame991Widget(),
                            ),
                            Positioned(
                              left: 242.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 751.0,
                              height: 307.0,
                              child: GeneratedFrame994Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
