import 'package:flutter/material.dart';

/* UndefinedNode labels
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLabelsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
