import 'package:flutter/material.dart';

/* UndefinedNode badges
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBadgesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
