import 'package:flutter/material.dart';
import 'package:flutterapp/ezbarterapp/generatedicdot_2widget/generated/GeneratedEllipse38Widget.dart';
import 'package:flutterapp/ezbarterapp/generatedicdot_2widget/generated/GeneratedEllipse40Widget.dart';
import 'package:flutterapp/ezbarterapp/generatedicdot_2widget/generated/GeneratedVectorWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ezbarterapp/generatedicdot_2widget/generated/GeneratedEllipse39Widget.dart';

/* Component ic/dot_2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIcdot_2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: TransformHelper.rotate(
            a: 1.00,
            b: -0.00,
            c: 0.00,
            d: 1.00,
            child: ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                width: 24.0,
                height: 24.0,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    overflow: Overflow.visible,
                    children: [
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentWidth = 1.0;
                          double scaleX =
                              (constraints.maxWidth * percentWidth) / 24.0;

                          double percentHeight = 1.0;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) / 24.0;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX: 0,
                                translateY: 0,
                                translateZ: 0,
                                scaleX: scaleX,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget2())
                          ]);
                        }),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentWidth = 0.125;
                          double scaleX =
                              (constraints.maxWidth * percentWidth) / 3.0;

                          double percentHeight = 0.125;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) / 3.0;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX:
                                    constraints.maxWidth * 0.4166666666666667,
                                translateY: constraints.maxHeight * 0.125,
                                translateZ: 0,
                                scaleX: scaleX,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedEllipse38Widget())
                          ]);
                        }),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentWidth = 0.125;
                          double scaleX =
                              (constraints.maxWidth * percentWidth) / 3.0;

                          double percentHeight = 0.125;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) / 3.0;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX:
                                    constraints.maxWidth * 0.4166666666666667,
                                translateY:
                                    constraints.maxHeight * 0.4583333333333333,
                                translateZ: 0,
                                scaleX: scaleX,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedEllipse39Widget())
                          ]);
                        }),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentWidth = 0.125;
                          double scaleX =
                              (constraints.maxWidth * percentWidth) / 3.0;

                          double percentHeight = 0.125;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) / 3.0;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX:
                                    constraints.maxWidth * 0.4166666666666667,
                                translateY:
                                    constraints.maxHeight * 0.7916666666666666,
                                translateZ: 0,
                                scaleX: scaleX,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedEllipse40Widget())
                          ]);
                        }),
                      )
                    ]),
              ),
            )));
  }
}
