import 'package:flutter/material.dart';

/* UndefinedNode check-box
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckboxWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
