import 'package:flutter/material.dart';

/* UndefinedNode Switch
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSwitchWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
