import 'package:flutter/material.dart';

/* UndefinedNode table
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTableWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
