import 'package:flutter/material.dart';
import 'package:flutterapp/ezbarterapp/generateduserswidget/generated/GeneratedComponent7Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ezbarterapp/generateduserswidget/generated/GeneratedFrame973Widget.dart';
import 'package:flutterapp/ezbarterapp/generateduserswidget/generated/GeneratedProperty1showmodalWidget.dart';
import 'package:flutterapp/ezbarterapp/generateduserswidget/generated/GeneratedFrame965Widget.dart';
import 'package:flutterapp/ezbarterapp/generateduserswidget/generated/GeneratedFrame975Widget.dart';
import 'package:flutterapp/ezbarterapp/generateduserswidget/generated/GeneratedNumbersWidget.dart';
import 'package:flutterapp/ezbarterapp/generateduserswidget/generated/GeneratedRecentactivityWidget.dart';

/* Frame Users
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUsersWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 900.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1295.0,
                      height: 900.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.09961389961389962;

                                final double height = constraints.maxHeight *
                                    0.024444444444444446;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.8926640926640926,
                                      y: constraints.maxHeight *
                                          0.39222222222222225,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRecentactivityWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 242.0,
                              top: 254.0,
                              right: null,
                              bottom: null,
                              width: 997.0,
                              height: 40.0,
                              child: GeneratedFrame975Widget(),
                            ),
                            Positioned(
                              left: 242.0,
                              top: 190.0,
                              right: null,
                              bottom: null,
                              width: 997.0,
                              height: 40.0,
                              child: GeneratedFrame965Widget(),
                            ),
                            Positioned(
                              left: 221.0,
                              top: 328.0,
                              right: null,
                              bottom: null,
                              width: 1057.0,
                              height: 478.0,
                              child: GeneratedFrame973Widget(),
                            ),
                            Positioned(
                              left: 1108.0,
                              top: 483.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 94.0,
                              child: GeneratedProperty1showmodalWidget(),
                            ),
                            Positioned(
                              left: 289.0,
                              top: 25.0,
                              right: null,
                              bottom: null,
                              width: 903.0,
                              height: 141.0,
                              child: GeneratedNumbersWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 235.0,
                              height: 900.0,
                              child: GeneratedComponent7Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
