import 'package:flutter/material.dart';

/* UndefinedNode dropdown/list-item
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDropdownlistitemWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
