import 'package:flutter/material.dart';
import 'package:flutterapp/ezbarterapp/generatedtablewidget1/generated/GeneratedTableWidget8.dart';
import 'package:flutterapp/ezbarterapp/generatedtablewidget1/generated/GeneratedTableWidget5.dart';
import 'package:flutterapp/ezbarterapp/generatedtablewidget1/generated/GeneratedTableWidget2.dart';
import 'package:flutterapp/ezbarterapp/generatedtablewidget1/generated/GeneratedTableWidget3.dart';
import 'package:flutterapp/ezbarterapp/generatedtablewidget1/generated/GeneratedTableWidget4.dart';
import 'package:flutterapp/ezbarterapp/generatedtablewidget1/generated/GeneratedTableWidget7.dart';
import 'package:flutterapp/ezbarterapp/generatedtablewidget1/generated/GeneratedTableWidget6.dart';

/* Component table
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTableWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1097.0,
        height: 518.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 1057.0,
                height: 76.0,
                child: GeneratedTableWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 1057.0,
                height: 59.0,
                child: GeneratedTableWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 1057.0,
                height: 59.0,
                child: GeneratedTableWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 1057.0,
                height: 59.0,
                child: GeneratedTableWidget5(),
              ),
              Positioned(
                left: 20.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 1057.0,
                height: 59.0,
                child: GeneratedTableWidget6(),
              ),
              Positioned(
                left: 20.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 1057.0,
                height: 59.0,
                child: GeneratedTableWidget7(),
              ),
              Positioned(
                left: 20.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 1057.0,
                height: 59.0,
                child: GeneratedTableWidget8(),
              )
            ]),
      ),
    ));
  }
}
