import 'package:flutter/material.dart';

/* UndefinedNode icons
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
