import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ezbarterapp/generateddropdowninputwidget/generated/GeneratedDropdownlistWidget.dart';
import 'package:flutterapp/ezbarterapp/generateddropdowninputwidget/generated/GeneratedIcarrowWidget.dart';

/* Component dropdown/input
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDropdowninputWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 249.0,
      height: 36.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(8.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(8.0),
              child: Container(
                color: Color.fromARGB(255, 246, 246, 246),
              ),
            ),
            Positioned(
              left: 12.0,
              top: null,
              right: null,
              bottom: null,
              width: 121.0,
              height: 24.0,
              child: TransformHelper.translate(
                  x: 0.00, y: 2.50, z: 0, child: GeneratedDropdownlistWidget()),
            ),
            Positioned(
              left: null,
              top: null,
              right: 12.0,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedIcarrowWidget(),
            )
          ]),
    ));
  }
}
