import 'package:flutter/material.dart';

/* UndefinedNode tab-bar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTabbarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
