import 'package:flutter/material.dart';

/* UndefinedNode sidebar-tabs
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSidebartabsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
