import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ezbarterapp/generatedcheckwidget/generated/GeneratedVectorWidget6.dart';
import 'package:flutterapp/ezbarterapp/generatedcheckwidget/generated/GeneratedVectorWidget5.dart';

/* Group Check
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 5.0,
      height: 5.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 1.0;
                double scaleX = (constraints.maxWidth * percentWidth) / 5.0;

                double percentHeight = 1.0;
                double scaleY = (constraints.maxHeight * percentHeight) / 5.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: 0,
                      translateY: 0,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget5())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.65625;
                double scaleX = (constraints.maxWidth * percentWidth) / 3.28125;

                double percentHeight = 0.4374804973602295;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    2.1874024868011475;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.1875,
                      translateY: constraints.maxHeight * 0.28127288818359375,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget6())
                ]);
              }),
            )
          ]),
    ));
  }
}
