import 'package:flutter/material.dart';

/* UndefinedNode input
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
