import 'package:flutter/material.dart';

/* UndefinedNode General
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGeneralWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
