import 'package:flutter/material.dart';

/* UndefinedNode pagination
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaginationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
