import 'package:flutter/material.dart';

/* UndefinedNode breadcrumbs
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBreadcrumbsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
