import 'package:flutter/material.dart';
import 'package:flutterapp/ezbarterapp/generatedgroup934widget/generated/GeneratedVectorWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ezbarterapp/generatedgroup934widget/generated/GeneratedVectorWidget4.dart';

/* Group Group 934
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup934Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 12.999801635742188,
      height: 13.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 1.2954660163975797;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 16.840801239013672;

                double percentHeight = 0.1151507359284621;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    1.4969595670700073;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.005106119550951928,
                      translateY: constraints.maxHeight * 0.9183673858642578,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget3())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 1.295469831153054;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 16.840850830078125;

                double percentHeight = 0.11515111189622146;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 1.496964454650879;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.08127916087117278,
                      translateY: constraints.maxHeight * 0.0006991022338087743,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget4())
                ]);
              }),
            )
          ]),
    ));
  }
}
